apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api
  labels:
    app: books-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
      - name: books-api
        # Replace with your actual Docker Hub or ACR registry path when pushed
        image: arpanpathak/books-api:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDRS
          # The internal DNS name we created in 02-services.yaml!
          value: "redis-cluster.redis.svc.cluster.local:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: password
        # Resources MUST be defined for HPA to work!
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
